---
# Install prerequisites for Zookeeper

- name: Ensure bash is installed
  ansible.builtin.apt:
    name: bash
    state: present
    update_cache: true

- name: Verify bash is available
  ansible.builtin.command: which bash
  register: zookeeper_bash_path
  changed_when: false

- name: Debug bash path
  ansible.builtin.debug:
    msg: "Bash is installed at {{ zookeeper_bash_path.stdout }}"

- name: Ensure zkServer.sh starts with correct bash shebang
  ansible.builtin.lineinfile:
    path: "{{ zookeeper_install_dir }}/apache-zookeeper-{{ zookeeper_version }}-bin/bin/zkServer.sh"
    regexp: '^#!'
    line: '#!/usr/bin/env bash'
    state: present
    backrefs: true

- name: Install core utilities
  ansible.builtin.apt:
    name:
      - coreutils
      - grep
      - sed
      - procps
    state: present
    update_cache: true
